[toolchain]
#%if chip.riscv
#%if option("stack-smashing-protection")
#+channel    = "nightly"
#%else
channel    = "{{ rust_toolchain }}"
#%endif
components = ["rust-src"]
targets = ["{{ chip.rust_target }}"]
#%else if chip.xtensa
#+channel = "{{ rust_toolchain }}"
#%endif
